class JapaneseCharacter {
  final String character;
  final String romanji;
  final bool isDakuon;
  final bool isYoon;

  JapaneseCharacter(this.character, this.romanji, {this.isDakuon = false, this.isYoon = false});
}

class Hiragana extends JapaneseCharacter {
  Hiragana(super.character, super.romanji, {super.isDakuon, super.isYoon});
}

class Katakana extends JapaneseCharacter {
  Katakana(super.character, super.romanji, {super.isDakuon, super.isYoon});
}

class HiraganaData {
  static List<Hiragana> hiraganaList = [
    // Basic Hiragana
    Hiragana('あ', 'a'),
    Hiragana('い', 'i'),
    Hiragana('う', 'u'),
    Hiragana('え', 'e'),
    Hiragana('お', 'o'),
    Hiragana('か', 'ka'),
    Hiragana('き', 'ki'),
    Hiragana('く', 'ku'),
    Hiragana('け', 'ke'),
    Hiragana('こ', 'ko'),
    Hiragana('が', 'ga', isDakuon: true),
    Hiragana('ぎ', 'gi', isDakuon: true),
    Hiragana('ぐ', 'gu', isDakuon: true),
    Hiragana('げ', 'ge', isDakuon: true),
    Hiragana('ご', 'go', isDakuon: true),
    Hiragana('さ', 'sa'),
    Hiragana('し', 'shi'),
    Hiragana('す', 'su'),
    Hiragana('せ', 'se'),
    Hiragana('そ', 'so'),
    Hiragana('ざ', 'za', isDakuon: true),
    Hiragana('じ', 'ji', isDakuon: true),
    Hiragana('ず', 'zu', isDakuon: true),
    Hiragana('ぜ', 'ze', isDakuon: true),
    Hiragana('ぞ', 'zo', isDakuon: true),
    Hiragana('た', 'ta'),
    Hiragana('ち', 'chi'),
    Hiragana('つ', 'tsu'),
    Hiragana('て', 'te'),
    Hiragana('と', 'to'),
    Hiragana('だ', 'da', isDakuon: true),
    Hiragana('ぢ', 'ji', isDakuon: true),
    Hiragana('づ', 'zu', isDakuon: true),
    Hiragana('で', 'de', isDakuon: true),
    Hiragana('ど', 'do', isDakuon: true),
    Hiragana('な', 'na'),
    Hiragana('に', 'ni'),
    Hiragana('ぬ', 'nu'),
    Hiragana('ね', 'ne'),
    Hiragana('の', 'no'),
    Hiragana('は', 'ha'),
    Hiragana('ひ', 'hi'),
    Hiragana('ふ', 'fu'),
    Hiragana('へ', 'he'),
    Hiragana('ほ', 'ho'),
    Hiragana('ば', 'ba', isDakuon: true),
    Hiragana('び', 'bi', isDakuon: true),
    Hiragana('ぶ', 'bu', isDakuon: true),
    Hiragana('べ', 'be', isDakuon: true),
    Hiragana('ぼ', 'bo', isDakuon: true),
    Hiragana('ぱ', 'pa', isDakuon: true),
    Hiragana('ぴ', 'pi', isDakuon: true),
    Hiragana('ぷ', 'pu', isDakuon: true),
    Hiragana('ぺ', 'pe', isDakuon: true),
    Hiragana('ぽ', 'po', isDakuon: true),
    Hiragana('ま', 'ma'),
    Hiragana('み', 'mi'),
    Hiragana('む', 'mu'),
    Hiragana('め', 'me'),
    Hiragana('も', 'mo'),
    Hiragana('や', 'ya'),
    Hiragana('-', '-'),
    Hiragana('ゆ', 'yu'),
    Hiragana('-', '-'),
    Hiragana('よ', 'yo'),
    Hiragana('ら', 'ra'),
    Hiragana('り', 'ri'),
    Hiragana('る', 'ru'),
    Hiragana('れ', 're'),
    Hiragana('ろ', 'ro'),
    Hiragana('わ', 'wa'),
    Hiragana('-', '-'),
    Hiragana('-', '-'),
    Hiragana('-', '-'),
    Hiragana('を', 'wo'),
    Hiragana('ん', 'n'),

    // Yoon (combined characters)
    Hiragana('じゃ', 'ja', isYoon: true),
    Hiragana('きゃ', 'ju', isYoon: true),
    Hiragana('じょ', 'jo', isYoon: true),
    Hiragana('ぢゃ', 'ja', isYoon: true),
    Hiragana('ぢゅ', 'ju', isYoon: true),
    Hiragana('ぢょ', 'jo', isYoon: true),
    Hiragana('きゃ', 'kya', isYoon: true),
    Hiragana('きゃ', 'kya', isYoon: true),
    Hiragana('きゅ', 'kyu', isYoon: true),
    Hiragana('きょ', 'kyo', isYoon: true),
    Hiragana('しゃ', 'sha', isYoon: true),
    Hiragana('しゅ', 'shu', isYoon: true),
    Hiragana('しょ', 'sho', isYoon: true),
    Hiragana('ちゃ', 'cha', isYoon: true),
    Hiragana('ちゅ', 'chu', isYoon: true),
    Hiragana('ちょ', 'cho', isYoon: true),
    Hiragana('にゃ', 'nya', isYoon: true),
    Hiragana('にゅ', 'nyu', isYoon: true),
    Hiragana('にょ', 'nyo', isYoon: true),
    Hiragana('ひゃ', 'hya', isYoon: true),
    Hiragana('ひゅ', 'hyu', isYoon: true),
    Hiragana('ひょ', 'hyo', isYoon: true),
    Hiragana('びゃ', 'bya', isYoon: true),
    Hiragana('びゅ', 'byu', isYoon: true),
    Hiragana('びょ', 'byo', isYoon: true),
    Hiragana('ぴゃ', 'pya', isYoon: true),
    Hiragana('ぴゅ', 'pyu', isYoon: true),
    Hiragana('ぴょ', 'pyo', isYoon: true),
    Hiragana('みゃ', 'mya', isYoon: true),
    Hiragana('みゅ', 'myu', isYoon: true),
    Hiragana('みょ', 'myo', isYoon: true),
    Hiragana('りゃ', 'rya', isYoon: true),
    Hiragana('りゅ', 'ryu', isYoon: true),
    Hiragana('りょ', 'ryo', isYoon: true),
  ];
}

class KatakanaData {
  static List<Katakana> katakanaList = [
    // Basic Katakana
    Katakana('ア', 'a'),
    Katakana('イ', 'i'),
    Katakana('ウ', 'u'),
    Katakana('エ', 'e'),
    Katakana('オ', 'o'),
    Katakana('カ', 'ka'),
    Katakana('キ', 'ki'),
    Katakana('ク', 'ku'),
    Katakana('ケ', 'ke'),
    Katakana('コ', 'ko'),
    Katakana('ガ', 'ga', isDakuon: true),
    Katakana('ギ', 'gi', isDakuon: true),
    Katakana('グ', 'gu', isDakuon: true),
    Katakana('ゲ', 'ge', isDakuon: true),
    Katakana('ゴ', 'go', isDakuon: true),
    Katakana('サ', 'sa'),
    Katakana('シ', 'shi'),
    Katakana('ス', 'su'),
    Katakana('セ', 'se'),
    Katakana('ソ', 'so'),
    Katakana('ザ', 'za', isDakuon: true),
    Katakana('ジ', 'ji', isDakuon: true),
    Katakana('ズ', 'zu', isDakuon: true),
    Katakana('ゼ', 'ze', isDakuon: true),
    Katakana('ゾ', 'zo', isDakuon: true),
    Katakana('タ', 'ta'),
    Katakana('チ', 'chi'),
    Katakana('ツ', 'tsu'),
    Katakana('テ', 'te'),
    Katakana('ト', 'to'),
    Katakana('ダ', 'da', isDakuon: true),
    Katakana('ヂ', 'ji', isDakuon: true),
    Katakana('ヅ', 'zu', isDakuon: true),
    Katakana('デ', 'de', isDakuon: true),
    Katakana('ド', 'do', isDakuon: true),
    Katakana('ナ', 'na'),
    Katakana('ニ', 'ni'),
    Katakana('ヌ', 'nu'),
    Katakana('ネ', 'ne'),
    Katakana('ノ', 'no'),
    Katakana('ハ', 'ha'),
    Katakana('ヒ', 'hi'),
    Katakana('フ', 'fu'),
    Katakana('ヘ', 'he'),
    Katakana('ホ', 'ho'),
    Katakana('バ', 'ba', isDakuon: true),
    Katakana('ビ', 'bi', isDakuon: true),
    Katakana('ブ', 'bu', isDakuon: true),
    Katakana('ベ', 'be', isDakuon: true),
    Katakana('ボ', 'bo', isDakuon: true),
    Katakana('パ', 'pa', isDakuon: true),
    Katakana('ピ', 'pi', isDakuon: true),
    Katakana('プ', 'pu', isDakuon: true),
    Katakana('ペ', 'pe', isDakuon: true),
    Katakana('ポ', 'po', isDakuon: true),
    Katakana('マ', 'ma'),
    Katakana('ミ', 'mi'),
    Katakana('ム', 'mu'),
    Katakana('メ', 'me'),
    Katakana('モ', 'mo'),
    Katakana('ヤ', 'ya'),
    Katakana('-', '-'),
    Katakana('ユ', 'yu'),
    Katakana('-', '-'),
    Katakana('ヨ', 'yo'),
    Katakana('ラ', 'ra'),
    Katakana('リ', 'ri'),
    Katakana('ル', 'ru'),
    Katakana('レ', 're'),
    Katakana('ロ', 'ro'),
    Katakana('ワ', 'wa'),
    Katakana('-', '-'),
    Katakana('-', '-'),
    Katakana('-', '-'),
    Katakana('ヲ', 'wo'),
    Katakana('ン', 'n'),

    // Yoon (combined characters)
    Katakana('イィ', 'yi', isYoon: true),
    Katakana('イェ', 'ye', isYoon: true),
    Katakana('ウァ', 'wa', isYoon: true),
    Katakana('ウィ', 'wi', isYoon: true),
    Katakana('ウゥ', 'wu', isYoon: true),
    Katakana('ウェ', 'we', isYoon: true),
    Katakana('ウォ', 'wo', isYoon: true),
    Katakana('ヴァ', 'ba', isYoon: true),
    Katakana('ヴィ', 'bi', isYoon: true),
    Katakana('ヴァ', 'ba', isYoon: true),
    Katakana('ヴェ', 'be', isYoon: true),
    Katakana('ヴォ', 'bo', isYoon: true),
    Katakana('ヴィェ', 'bye', isYoon: true),
    Katakana('キェ', 'kye', isYoon: true),
    Katakana('ギェ', 'gie', isYoon: true),
    Katakana('クァ', 'kwa', isYoon: true),
    Katakana('クィ', 'kwi', isYoon: true),
    Katakana('クェ', 'kwe', isYoon: true),
    Katakana('クォ', 'kwo', isYoon: true),
    Katakana('グァ', 'gwa', isYoon: true),
    Katakana('グィ', 'gwi', isYoon: true),
    Katakana('グェ', 'gwe', isYoon: true),
    Katakana('グォ', 'gwo', isYoon: true),
    Katakana('シェ', 'she', isYoon: true),
    Katakana('ジェ', 'je', isYoon: true),
    Katakana('スィ', 'si', isYoon: true),
    Katakana('ズィ', 'zi', isYoon: true),
    Katakana('チェ', 'che', isYoon: true),
    Katakana('ツァ', 'tsa', isYoon: true),
    Katakana('ツィ', 'tsi', isYoon: true),
    Katakana('ツェ', 'tse', isYoon: true),
    Katakana('ツォ', 'tso', isYoon: true),
    Katakana('ティ', 'ti', isYoon: true),
    Katakana('テゥ', 'tu', isYoon: true),
    Katakana('ディ', 'di', isYoon: true),
    Katakana('デゥ', 'du', isYoon: true),
    Katakana('ニェ', 'nye', isYoon: true),
    Katakana('ヒェ', 'hye', isYoon: true),
    Katakana('ビェ', 'bye', isYoon: true),
    Katakana('ピェ', 'pye', isYoon: true),
    Katakana('ファ', 'fa', isYoon: true),
    Katakana('フィ', 'fi', isYoon: true),
    Katakana('フェ', 'fe', isYoon: true),
    Katakana('フォ', 'fo', isYoon: true),
    Katakana('フィェ', 'fye', isYoon: true),
    Katakana('ホゥ', 'hu', isYoon: true),
    Katakana('ミェ', 'mye', isYoon: true),
    Katakana('リェ', 'rye', isYoon: true),
    Katakana('ラ゜', 'la', isYoon: true),
    Katakana('リ゜', 'li', isYoon: true),
    Katakana('ル゜', 'lu',isYoon: true),
    Katakana('レ゜', 'le',isYoon: true),
    Katakana('ル゜', 'lu',isYoon: true),
    Katakana('ロ゜', 'lo',isYoon: true),
    Katakana('キャ', 'kya', isYoon: true),
    Katakana('キュ', 'kyu', isYoon: true),
    Katakana('キョ', 'kyo', isYoon: true),
    Katakana('シャ', 'sha', isYoon: true),
    Katakana('シュ', 'shu', isYoon: true),
    Katakana('ショ', 'sho', isYoon: true),
    Katakana('チャ', 'cha', isYoon: true),
    Katakana('チュ', 'chu', isYoon: true),
    Katakana('チョ', 'cho', isYoon: true),
    Katakana('ニャ', 'nya', isYoon: true),
    Katakana('ニュ', 'nyu', isYoon: true),
    Katakana('ニョ', 'nyo', isYoon: true),
    Katakana('ヒャ', 'hya', isYoon: true),
    Katakana('ヒュ', 'hyu', isYoon: true),
    Katakana('ヒョ', 'hyo', isYoon: true),
    Katakana('ビャ', 'bya', isYoon: true),
    Katakana('ビュ', 'byu', isYoon: true),
    Katakana('ビョ', 'byo', isYoon: true),
    Katakana('ピャ', 'pya', isYoon: true),
    Katakana('ピュ', 'pyu', isYoon: true),
    Katakana('ピョ', 'pyo', isYoon: true),
    Katakana('ミャ', 'mya', isYoon: true),
    Katakana('ミュ', 'myu', isYoon: true),
    Katakana('ミョ', 'myo', isYoon: true),
    Katakana('リャ', 'rya', isYoon: true),
    Katakana('リュ', 'ryu', isYoon: true),
    Katakana('リョ', 'ryo', isYoon: true),
  ];
}
