class Kanji {
  final int id;
  final String character;
  final List<String> onyomiLatin;
  final List<String> onyomiKana;
  final List<String> kunyomiLatin;
  final List<String> kunyomiKana;
  final String meaning;

  Kanji({
    required this.id,
    required this.character,
    required this.onyomiLatin,
    required this.onyomiKana,
    required this.kunyomiLatin,
    required this.kunyomiKana,
    required this.meaning,
  });
}
List<Kanji> kanjiList = [
  Kanji(
    id: 1,
    character: '日',
    onyomiLatin: ['nichi', 'jitsu'],
    onyomiKana: ['ニチ', 'ジツ'],
    kunyomiLatin: ['hi', '-bi', '-ka'],
    kunyomiKana: ['ひ', '-び', '-か'],
    meaning: 'day, sun, Japan, counter for days',
  ),
  Kanji(
    id: 2,
    character: '一',
    onyomiLatin: ['ichi'],
    onyomiKana: ['イチ'],
    kunyomiLatin: ['hito(tsu)'],
    kunyomiKana: ['ひと(つ)'],
    meaning: 'one',
  ),
  Kanji(
    id: 3,
    character: '国',
    onyomiLatin: ['koku'],
    onyomiKana: ['コク'],
    kunyomiLatin: ['kuni'],
    kunyomiKana: ['くに'],
    meaning: 'country',
  ),
  Kanji(
    id: 4,
    character: '人',
    onyomiLatin: ['jin', 'nin'],
    onyomiKana: ['ジン', 'ニン'],
    kunyomiLatin: ['hito'],
    kunyomiKana: ['ひと'],
    meaning: 'person',
  ),
  Kanji(
    id: 5,
    character: '年',
    onyomiLatin: ['nen'],
    onyomiKana: ['ネン'],
    kunyomiLatin: ['toshi'],
    kunyomiKana: ['とし'],
    meaning: 'year, counter for years',
  ),
  Kanji(
    id: 6,
    character: '大',
    onyomiLatin: ['dai', 'tai'],
    onyomiKana: ['ダイ', 'タイ'],
    kunyomiLatin: ['oo(kii)'],
    kunyomiKana: ['おお(きい)'],
    meaning: 'large, big',
  ),
  Kanji(
    id: 7,
    character: '十',
    onyomiLatin: ['juu'],
    onyomiKana: ['ジュウ'],
    kunyomiLatin: ['tou', 'to'],
    kunyomiKana: ['とお', 'と'],
    meaning: 'ten, 10',
  ),
  Kanji(
    id: 8,
    character: '二',
    onyomiLatin: ['ni', 'ji'],
    onyomiKana: ['ニ', 'ジ'],
    kunyomiLatin: ['futa(tsu)'],
    kunyomiKana: ['ふた(つ)'],
    meaning: 'two, 2',
  ),
  Kanji(
    id: 9,
    character: '本',
    onyomiLatin: ['hon'],
    onyomiKana: ['ホン'],
    kunyomiLatin: ['moto'],
    kunyomiKana: ['もと'],
    meaning: 'book, present, true, counter for long cylindrical things',
  ),
  Kanji(
    id: 10,
    character: '中',
    onyomiLatin: ['chuu'],
    onyomiKana: ['チュウ'],
    kunyomiLatin: ['naka', 'uchi', 'ata(ru)'],
    kunyomiKana: ['なか', 'うち', 'あた(る)'],
    meaning: 'in, inside, middle, mean, center',
  ),
  Kanji(
    id: 11,
    character: '長',
    onyomiLatin: ['chou'],
    onyomiKana: ['チョウ'],
    kunyomiLatin: ['naga(i)', 'osa'],
    kunyomiKana: ['なが(い)', 'おさ'],
    meaning: 'long, leader, superior, senior',
  ),
  Kanji(
    id: 12,
    character: '出',
    onyomiLatin: ['shutsu', 'sui'],
    onyomiKana: ['シュツ', 'スイ'],
    kunyomiLatin: ['de(ru)', 'da(su)', 'i(deru)'],
    kunyomiKana: ['で(る)', 'だ(す)', 'い(でる)'],
    meaning: 'exit, leave, go out',
  ),
  Kanji(
    id: 13,
    character: '三',
    onyomiLatin: ['san'],
    onyomiKana: ['サン'],
    kunyomiLatin: ['mi(tsu)'],
    kunyomiKana: ['み(つ)'],
    meaning: 'three, 3',
  ),
  Kanji(
    id: 14,
    character: '時',
    onyomiLatin: ['ji'],
    onyomiKana: ['ジ'],
    kunyomiLatin: ['toki', 'doki'],
    kunyomiKana: ['とき', '-どき'],
    meaning: 'time, hour',
  ),
  Kanji(
    id: 15,
    character: '行',
    onyomiLatin: ['kou', 'gyou', 'an'],
    onyomiKana: ['コウ', 'ギョウ', 'アン'],
    kunyomiLatin: ['i(ku)', 'yu(ku)', 'okona(u)'],
    kunyomiKana: ['い(く)', 'ゆ(く)', 'おこな(う)'],
    meaning: 'going, journey, carry out, line, row',
  ),
  Kanji(
    id: 16,
    character: '見',
    onyomiLatin: ['ken'],
    onyomiKana: ['ケン'],
    kunyomiLatin: ['mi(ru)', 'mi(seru)'],
    kunyomiKana: ['み(る)', 'み(せる)'],
    meaning: 'see, hopes, chances, idea, opinion, look at, visible',
  ),
  Kanji(
    id: 17,
    character: '月',
    onyomiLatin: ['getsu', 'gatsu'],
    onyomiKana: ['ゲツ', 'ガツ'],
    kunyomiLatin: ['tsuki'],
    kunyomiKana: ['つき'],
    meaning: 'month, moon',
  ),
  Kanji(
    id: 18,
    character: '分',
    onyomiLatin: ['bun', 'fun', 'bu'],
    onyomiKana: ['ブン', 'フン', 'ブ'],
    kunyomiLatin: ['wa(keru)'],
    kunyomiKana: ['わ(ける)'],
    meaning: 'part, minute of time, understand',
  ),
  Kanji(
    id: 19,
    character: '後',
    onyomiLatin: ['go', 'kou'],
    onyomiKana: ['ゴ', 'コウ'],
    kunyomiLatin: ['nochi', 'ushi(ro)', 'ato'],
    kunyomiKana: ['のち', 'うし(ろ)', 'あと'],
    meaning: 'behind, back, later',
  ),
  Kanji(
    id: 20,
    character: '前',
    onyomiLatin: ['zen'],
    onyomiKana: ['ゼン'],
    kunyomiLatin: ['mae'],
    kunyomiKana: ['まえ'],
    meaning: 'in front, before',
  ),
  Kanji(
    id: 21,
    character: '生',
    onyomiLatin: ['sei', 'shou'],
    onyomiKana: ['セイ', 'ショウ'],
    kunyomiLatin: ['i(kiru)', 'u(mu)', 'o(u)', 'ha(eru)', 'nama'],
    kunyomiKana: ['い(きる)', 'う(む)', 'お(う)', 'は(える)', 'なま'],
    meaning: 'life, genuine, birth',
  ),
  Kanji(
    id: 22,
    character: '五',
    onyomiLatin: ['go'],
    onyomiKana: ['ゴ'],
    kunyomiLatin: ['itsu(tsu)'],
    kunyomiKana: ['いつ(つ)'],
    meaning: 'five, 5',
  ),
  Kanji(
    id: 23,
    character: '間',
    onyomiLatin: ['kan', 'ken'],
    onyomiKana: ['カン', 'ケン'],
    kunyomiLatin: ['aida', 'ma', 'ai'],
    kunyomiKana: ['あいだ', 'ま', 'あい'],
    meaning: 'interval, space',
  ),
  Kanji(
    id: 24,
    character: '上',
    onyomiLatin: ['jou', 'shou', 'shan'],
    onyomiKana: ['ジョウ', 'ショウ', 'シャン'],
    kunyomiLatin: ['ue', 'uwa', 'kami', 'a(geru)', 'nobo(ru)', 'tatematsu(ru)'],
    kunyomiKana: ['うえ', 'うわ', 'かみ', 'あ(げる)', 'のぼ(る)', 'たてまつ(る)'],
    meaning: 'above, up',
  ),
  Kanji(
    id: 25,
    character: '東',
    onyomiLatin: ['tou'],
    onyomiKana: ['トウ'],
    kunyomiLatin: ['higashi'],
    kunyomiKana: ['ひがし'],
    meaning: 'east',
  ),
  Kanji(
    id: 26,
    character: '四',
    onyomiLatin: ['shi'],
    onyomiKana: ['シ'],
    kunyomiLatin: ['yo(tsu)', 'yon'],
    kunyomiKana: ['よ(つ)', 'よん'],
    meaning: 'four, 4',
  ),
  Kanji(
    id: 27,
    character: '今',
    onyomiLatin: ['kon', 'kin'],
    onyomiKana: ['コン', 'キン'],
    kunyomiLatin: ['ima'],
    kunyomiKana: ['いま'],
    meaning: 'now; the present',
  ),
  Kanji(
    id: 28,
    character: '金',
    onyomiLatin: ['kin', 'kon', 'gon'],
    onyomiKana: ['キン', 'コン', 'ゴン'],
    kunyomiLatin: ['kane', 'kana', 'gane'],
    kunyomiKana: ['かね', 'かな', 'がね'],
    meaning: 'gold',
  ),
  Kanji(
    id: 29,
    character: '九',
    onyomiLatin: ['kyuu', 'ku'],
    onyomiKana: ['キュウ', 'ク'],
    kunyomiLatin: ['kokono(tsu)'],
    kunyomiKana: ['ここの(つ)'],
    meaning: 'nine',
  ),
  Kanji(
    id: 30,
    character: '入',
    onyomiLatin: ['nyuu'],
    onyomiKana: ['ニュウ'],
    kunyomiLatin: ['i(ru)', 'hai(ru)'],
    kunyomiKana: ['い(る)', 'はい(る)'],
    meaning: 'enter, insert',
  ),
  Kanji(
    id: 31,
    character: '学',
    onyomiLatin: ['gaku'],
    onyomiKana: ['ガク'],
    kunyomiLatin: ['mana(bu)'],
    kunyomiKana: ['まな(ぶ)'],
    meaning: 'study, learning, science',
  ),
  Kanji(
    id: 32,
    character: '高',
    onyomiLatin: ['kou'],
    onyomiKana: ['コウ'],
    kunyomiLatin: ['taka(i)'],
    kunyomiKana: ['たか(い)'],
    meaning: 'tall, high, expensive',
  ),
  Kanji(
    id: 33,
    character: '円',
    onyomiLatin: ['en'],
    onyomiKana: ['エン'],
    kunyomiLatin: ['maru(i)'],
    kunyomiKana: ['まる(い)'],
    meaning: 'circle, yen, round',
  ),
  Kanji(
    id: 34,
    character: '子',
    onyomiLatin: ['shi', 'su', 'tsu'],
    onyomiKana: ['シ', 'ス', 'ツ'],
    kunyomiLatin: ['ko', 'ne'],
    kunyomiKana: ['こ', 'ね'],
    meaning: 'child',
  ),
  Kanji(
    id: 35,
    character: '外',
    onyomiLatin: ['gai', 'ge'],
    onyomiKana: ['ガイ', 'ゲ'],
    kunyomiLatin: ['soto', 'hoka', 'hazu-', 'to-'],
    kunyomiKana: ['そと', 'ほか', 'はず(す)', 'と-'],
    meaning: 'outside',
  ),
  Kanji(
    id: 36,
    character: '八',
    onyomiLatin: ['hachi'],
    onyomiKana: ['ハチ'],
    kunyomiLatin: ['ya(tsu)', 'you'],
    kunyomiKana: ['や(つ)', 'よう'],
    meaning: 'eight, 8',
  ),
  Kanji(
    id: 37,
    character: '六',
    onyomiLatin: ['roku'],
    onyomiKana: ['ロク'],
    kunyomiLatin: ['mu(tsu)', 'mui'],
    kunyomiKana: ['む(つ)', 'むい'],
    meaning: 'six, 6',
  ),
  Kanji(
    id: 38,
    character: '下',
    onyomiLatin: ['ka', 'ge'],
    onyomiKana: ['カ', 'ゲ'],
    kunyomiLatin: ['shita', 'shimo', 'moto', 'sa(geru)', 'kuda(ru)', 'o(rosu)'],
    kunyomiKana: ['した', 'しも', 'もと', 'さ(げる)', 'くだ(る)', 'お(ろす)'],
    meaning: 'below, down, descend, give, low, inferior',
  ),
  Kanji(
    id: 39,
    character: '来',
    onyomiLatin: ['rai', 'tai'],
    onyomiKana: ['ライ', 'タイ'],
    kunyomiLatin: ['kuru', 'kitaru', 'ki', 'ko'],
    kunyomiKana: ['く.る', 'きた.る', 'き', 'こ'],
    meaning: 'come, due, next, cause, become',
  ),
  Kanji(
    id: 40,
    character: '気',
    onyomiLatin: ['ki', 'ke'],
    onyomiKana: ['キ', 'ケ'],
    kunyomiLatin: ['iki'],
    kunyomiKana: ['いき'],
    meaning: 'spirit, mind, air, atmosphere, mood',
  ),
  Kanji(
    id: 41,
    character: '小',
    onyomiLatin: ['shou'],
    onyomiKana: ['ショウ'],
    kunyomiLatin: ['chii(sai)', 'ko-', 'o-', 'sa-'],
    kunyomiKana: ['ちい(さい)', 'こ-', 'お-', 'さ-'],
    meaning: 'little, small',
  ),
  Kanji(
    id: 42,
    character: '七',
    onyomiLatin: ['shichi'],
    onyomiKana: ['シチ'],
    kunyomiLatin: ['nana(tsu)', 'nano'],
    kunyomiKana: ['なな(つ)', 'なの'],
    meaning: 'seven, 7',
  ),
  Kanji(
    id: 43,
    character: '山',
    onyomiLatin: ['san', 'sen'],
    onyomiKana: ['サン', 'セン'],
    kunyomiLatin: ['yama'],
    kunyomiKana: ['やま'],
    meaning: 'mountain',
  ),
  Kanji(
    id: 44,
    character: '話',
    onyomiLatin: ['wa'],
    onyomiKana: ['ワ'],
    kunyomiLatin: ['hana(su)', 'hanashi'],
    kunyomiKana: ['はな(す)', 'はなし'],
    meaning: 'tale, talk',
  ),
  Kanji(
    id: 45,
    character: '女',
    onyomiLatin: ['jo'],
    onyomiKana: ['ジョ'],
    kunyomiLatin: ['onnna', 'me'],
    kunyomiKana: ['おんな', 'め'],
    meaning: 'woman, female',
  ),
  Kanji(
    id: 46,
    character: '北',
    onyomiLatin: ['hoku'],
    onyomiKana: ['ホク'],
    kunyomiLatin: ['kita'],
    kunyomiKana: ['きた'],
    meaning: 'north',
  ),
  Kanji(
    id: 47,
    character: '午',
    onyomiLatin: ['go'],
    onyomiKana: ['ゴ'],
    kunyomiLatin: ['uma'],
    kunyomiKana: ['うま'],
    meaning: 'noon, sign of the horse',
  ),
  Kanji(
    id: 48,
    character: '百',
    onyomiLatin: ['hyaku', 'byaku'],
    onyomiKana: ['ヒャク', 'ビャク'],
    kunyomiLatin: ['momo'],
    kunyomiKana: ['もも'],
    meaning: 'hundred',
  ),
  Kanji(
    id: 49,
    character: '書',
    onyomiLatin: ['sho'],
    onyomiKana: ['ショ'],
    kunyomiLatin: ['kaku'],
    kunyomiKana: ['か(く)'],
    meaning: 'write',
  ),
  Kanji(
    id: 50,
    character: '先',
    onyomiLatin: ['sen'],
    onyomiKana: ['セン'],
    kunyomiLatin: ['saki', 'ma(zu)'],
    kunyomiKana: ['さき', 'ま(ず)'],
    meaning: 'before, ahead, previous, future, precedence',
  ),
  Kanji(
    id: 51,
    character: '名',
    onyomiLatin: ['mei', 'myou'],
    onyomiKana: ['メイ', 'ミョウ'],
    kunyomiLatin: ['na'],
    kunyomiKana: ['な'],
    meaning: 'name, noted, distinguished, reputation',
  ),
  Kanji(
    id: 52,
    character: '川',
    onyomiLatin: ['sen'],
    onyomiKana: ['セン'],
    kunyomiLatin: ['kawa'],
    kunyomiKana: ['かわ'],
    meaning: 'river, stream',
  ),
  Kanji(
    id: 53,
    character: '千',
    onyomiLatin: ['sen'],
    onyomiKana: ['セン'],
    kunyomiLatin: ['chi'],
    kunyomiKana: ['ち'],
    meaning: 'thousand',
  ),
  Kanji(
    id: 54,
    character: '水',
    onyomiLatin: ['sui'],
    onyomiKana: ['スイ'],
    kunyomiLatin: ['mizu'],
    kunyomiKana: ['みず'],
    meaning: 'water',
  ),
  Kanji(
    id: 55,
    character: '半',
    onyomiLatin: ['han'],
    onyomiKana: ['ハン'],
    kunyomiLatin: ['naka(ba)'],
    kunyomiKana: ['なか(ば)'],
    meaning: 'half, middle, odd number, semi-',
  ),
  Kanji(
    id: 56,
    character: '男',
    onyomiLatin: ['dan', 'nan'],
    onyomiKana: ['ダン', 'ナン'],
    kunyomiLatin: ['otoko', 'o'],
    kunyomiKana: ['おとこ', 'お'],
    meaning: 'male; man',
  ),
  Kanji(
    id: 57,
    character: '西',
    onyomiLatin: ['sei', 'sai'],
    onyomiKana: ['セイ', 'サイ'],
    kunyomiLatin: ['nishi'],
    kunyomiKana: ['にし'],
    meaning: 'west',
  ),
  Kanji(
    id: 60,
    character: '語',
    onyomiLatin: ['go'],
    onyomiKana: ['ゴ'],
    kunyomiLatin: ['kata(ru)'],
    kunyomiKana: ['かた(る)'],
    meaning: 'word, speech, language',
  ),
  Kanji(
    id: 61,
    character: '土',
    onyomiLatin: ['do', 'to'],
    onyomiKana: ['ド', 'ト'],
    kunyomiLatin: ['tsuchi'],
    kunyomiKana: ['つち'],
    meaning: 'soil, earth, ground',
  ),
  Kanji(
    id: 62,
    character: '木',
    onyomiLatin: ['boku', 'moku'],
    onyomiKana: ['ボク', 'モク'],
    kunyomiLatin: ['ki', 'ko'],
    kunyomiKana: ['き', 'こ-'],
    meaning: 'tree, wood',
  ),
  Kanji(
    id: 63,
    character: '聞',
    onyomiLatin: ['bun', 'mon'],
    onyomiKana: ['ブン', 'モン'],
    kunyomiLatin: ['ki(ku)'],
    kunyomiKana: ['き(く)'],
    meaning: 'to hear; to listen; to ask',
  ),
  Kanji(
    id: 64,
    character: '食',
    onyomiLatin: ['shoku', 'jiki'],
    onyomiKana: ['ショク', 'ジキ'],
    kunyomiLatin: ['k(u)', 'ta(beru)', 'ha(mu)'],
    kunyomiKana: ['く(う)', 'た(べる)', 'は(む)'],
    meaning: 'eat, food',
  ),
  Kanji(
    id: 65,
    character: '車',
    onyomiLatin: ['sha'],
    onyomiKana: ['シャ'],
    kunyomiLatin: ['kuruma'],
    kunyomiKana: ['くるま'],
    meaning: 'car, wheel',
  ),
  Kanji(
    id: 66,
    character: '何',
    onyomiLatin: ['ka'],
    onyomiKana: ['カ'],
    kunyomiLatin: ['nani', 'nan'],
    kunyomiKana: ['なに', 'なん'],
    meaning: 'what',
  ),
  Kanji(
    id: 67,
    character: '南',
    onyomiLatin: ['nan', 'na'],
    onyomiKana: ['ナン', 'ナ'],
    kunyomiLatin: ['minami'],
    kunyomiKana: ['みなみ'],
    meaning: 'south',
  ),
  Kanji(
    id: 68,
    character: '万',
    onyomiLatin: ['man', 'ban'],
    onyomiKana: ['マン', 'バン'],
    kunyomiLatin: ['yoro(zu)'],
    kunyomiKana: ['よろ(ず)'],
    meaning: 'ten thousand, 10,000',
  ),
  Kanji(
    id: 69,
    character: '母',
    onyomiLatin: ['bo'],
    onyomiKana: ['ボ'],
    kunyomiLatin: ['haha', 'kaha'],
    kunyomiKana: ['はは', 'かは'],
    meaning: 'mother',
  ),
  Kanji(
    id: 70,
    character: '火',
    onyomiLatin: ['ka'],
    onyomiKana: ['カ'],
    kunyomiLatin: ['hi'],
    kunyomiKana: ['ひ'],
    meaning: 'fire',
  ),
  Kanji(
    id: 71,
    character: '犬',
    onyomiLatin: ['ken'],
    onyomiKana: ['ケン'],
    kunyomiLatin: ['inu'],
    kunyomiKana: ['いぬ'],
    meaning: 'dog',
  ),
  Kanji(
    id: 72,
    character: '耳',
    onyomiLatin: ['ji'],
    onyomiKana: ['ジ'],
    kunyomiLatin: ['mimi'],
    kunyomiKana: ['みみ'],
    meaning: 'ear',
  ),
  Kanji(
    id: 73,
    character: '手',
    onyomiLatin: ['shu'],
    onyomiKana: ['シュ'],
    kunyomiLatin: ['te'],
    kunyomiKana: ['て'],
    meaning: 'hand',
  ),
  Kanji(
    id: 74,
    character: '毎',
    onyomiLatin: ['mai'],
    onyomiKana: ['マイ'],
    kunyomiLatin: ['te'],
    kunyomiKana: ['て'],
    meaning: 'every',
  ),
  Kanji(
    id: 75,
    character: '読',
    onyomiLatin: ['doku', 'toku'],
    onyomiKana: ['ドク', 'トク'],
    kunyomiLatin: ['yo(mu)', 'yo(meru)'],
    kunyomiKana: ['よ(む)', 'よ(める)'],
    meaning: 'read',
  ),
  Kanji(
    id: 76,
    character: '友',
    onyomiLatin: ['yuu'],
    onyomiKana: ['ユウ'],
    kunyomiLatin: ['tomo'],
    kunyomiKana: ['とも'],
    meaning: 'friend',
  ),
  Kanji(
    id: 77,
    character: '早',
    onyomiLatin: ['sou'],
    onyomiKana: ['ソウ'],
    kunyomiLatin: ['haya(i)', 'haya(me)', 'haya(ru)', 'sai'],
    kunyomiKana: ['はや(い)', 'はや(め)', 'はや(る)', 'さい'],
    meaning: 'already, fast, early',
  ),
  Kanji(
    id: 78,
    character: '行',
    onyomiLatin: ['gyou', 'an'],
    onyomiKana: ['ギョウ', 'アン'],
    kunyomiLatin: ['i(ku)', 'yu(ku)', 'okona(u)'],
    kunyomiKana: ['い(く)', 'ゆ(く)', 'おこな(う)'],
    meaning: 'going, journey, carry out, line, row',
  ),
  Kanji(
    id: 79,
    character: '草',
    onyomiLatin: ['sou'],
    onyomiKana: ['ソウ'],
    kunyomiLatin: ['kusa'],
    kunyomiKana: ['くさ'],
    meaning: 'grass, weeds, herbs, pasture, write, draft',
  ),
  Kanji(
    id: 80,
    character: '多',
    onyomiLatin: ['ta'],
    onyomiKana: ['タ'],
    kunyomiLatin: ['oo(i)'],
    kunyomiKana: ['おお(い)'],
    meaning: 'many, frequent, much',
  ),
];
